# Site settings
title: Salvatore Francesco Spoto
twitter_username: FrancescoSSpot1
name: Salvatore Francesco Spoto

# Build settings
markdown: kramdown

#List of interesting Github repo/projects to include - optional
github:
 - https://github.com/salvatorespoto/GLTFViewer
 
#User specific content
#Links that will appear in the navbar
primarylinks:
# - title: Blog
#   url: https://automateddeveloper.blogspot.com/
# - title: GitHub
#   url: https://github.com/robhinds
# - title: StackOverflow
#   url: https://stackoverflow.com/users/258813/rhinds
# - title: DZone
#   url: https://dzone.com/users/899489/rhinds.html
# - title: LinkedIn
#   url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1

#Any buzzword skills you want to include
skills:
 - C++ 17
 - Direct3D 12
 - HLSL
 - PIX
 - Visual Studio
 - Math 
 - OpenGL
 - GLSL
 - Visual Studio Code
 - Java
 - Java Spring
 - Eclipse
 - MySQL / PostgreSQL / SQL
 - Javascript
 - HTML
 - CSS
 - Photoshop
 
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: C++
   start: 2020
   end: now
   description: 
 - title: Java back-end developer
   start: 2016
   end: 2020
   employer: Synthesis3
   description: Synthesis3 is a company that manly develop software realeated to the automotive field, serving big clients like Iveco or FTP Powertrain. I worked manly as Java Spring back-developer, but developed also some front-end parts if needed. 
 - title: Full stack developer - Angular and PHP
   start: 2015
   end: 2016
   employer: JumpOn
   description: JumpOn was a start-up who provided mobility as a service. I worked bot as front-end Angular developer that back-end PHP developer.
 - title: Front-end developer
   start: 2015
   end: 2016
   employer: I.See
   description: I.See is a company that develop Radioterapy Treatment Planning System software. As front end programmer I developed the user interface to visualize the TAC scans and define interactvely the treatment plan.
 - title: Generalist programmer
   start: 2013
   end: 2015
   employer: University of Turin
   description: As contract researcher I develop in collaboration with several research team I developed software in the field of social netwrok, recommending system and streamibng.
 - title: Full stack developer - Javascript, PHP
   start: 2013
   end: 2015
   employer: Institut National de Recherche, France
   description: Development of mobile applciation that implements cistize cervses
 - title: C++ OpenGL Developer
   start: 2013
   end: 2015
   employer: Institut National de Recherche, France
   description: As contract researcher I develop in collaboration with several research team I developed software in the field of social netwrok, recommending system and streamibng.
 - title: C++  Developer
   start: 2001
   end: 2002
   employer: Telecom Italia Lab
   description: As contract researcher I develop in collaboration with several research team I developed software in the field of social netwrok, recommending system and streamibng.
 
#Education is required
education:
 - level: Ph.D Computer Science
   date: 2011
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham
 - level: Master Degree in Computer Science
   date: 2004
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham


 
#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  I am a computer scientist and a passionate software developer with more than 20 years of experience working in technology. <br/><br/>
  I worked both in the development of enterprise applications and in applied university research. Durign these years i buildt a strong mathematical background, 
   Skills in 3D and game related algorithms. Always in love with video games.
  
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>C++</strong>: Currently I am developing my projects using C++ 17. I worked in the past on projects that used previous versions of the language, both at University and at Private companies <br/>
   <strong>Java</strong>: I worked I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
   <strong>Web Development Javascript / HTML / CSS / PHP </strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
   <strong>Phyton</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
