# Site settings
title: Salvatore Spoto
twitter_username: FrancescoSSpot1
name: Salvatore Spoto

# Build settings
markdown: kramdown

#List of interesting Github repo/projects to include - optional
github:
 projects:
 - title: glTF Viewer DirectX 12
   description: |
    A viewer of the <a href="https://github.com/KhronosGroup/glTF/tree/master/specification/2.0">glTF</a> file format, implemented in DirectX 12. 
    <p> This project aims to realize a software that can load and render files written according to the 
    <a href="https://github.com/KhronosGroup/glTF/tree/master/specification/2.0">glTF</a> specification. 
    The software is implemented in C++, DirectX 12 and HLSL.</br></br>
    GlTF is a specification from KhronosGroup for a file format that can describe:</br>
    <ul> <li>3D geometry </li>
    <li>materials, described according to a <a href="https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#implementation">shading model</a> described in the specification</li>
    <li> animations </li></ul>
    </br>
    This is an ongoing project actually under development. Check out the <a href="https://github.com/salvatorespoto/GLTFViewer/projects/1">project roadmap</a>.</br>
    Current supported features are:</br>
    <ul> <li>Scenes: scene, nodes hierarchy, node transformation </li> 
    <li> Meshes: geometry, all the attributes are supported (position, normal, tangent, textcoord_0, etc.), instantiation </li> 
    <li>  Materials: textures, images, samples, additional maps (normal, occlusion, emission)</li>
    <li> Shading model</li>
    </ul></br>
   
   optionalImage: img/gltfViewer.jpg
   optionalImageLink: https://youtu.be/tEVuwpKdP4A
   repository: salvatorespoto/GLTFViewer
 - title: Nonagon
   description: A prototype game made for the weekly game jam 
   optionalImage: img/nonagon.jpg
   optionalImageLink: https://youtu.be/gAjW-B9WufE
 - title: They are alive
   description: A prototype game made for the weekly game jam. Here the link on <a href="https://frankiess.itch.io/they-are-alive">itch.io</a>
   optionalImage: img/theyarealive.png
   optionalImageLink: https://youtu.be/gPahd7wHmjA
 
 #List of ShaderToy shaders
shadertoy:
  shaders:
  - title: Baking normal maps
    shaderId: wstyzH
    description: |
     <br>Here I demonstrate the process of backing the normal maps from a high detailed (HD) object to the tangent space of a low detailed (LD) object.
     Rays are casted from outside the objects, normal are sampled from the HD model and mapped to the LD one. This mapping then transformed in the LD tangent space.
     The HD object is dynamic changing and the normal are sampled in real time, so you can see how the changes in the HD model affect the LD. <br><br>
     <a target="_blank" href="https://shadertoy.com/view/wstyzH"> Link to the shader </a>
     
  - title: Wireframe rasterizer
    shaderId: wtVSDh
    description: |
     <br>A little wireframe rasterizer. It uses the same transformations pipeline that OpenGL:
     Object -> Eye -> Clip -> NDC -> Window. When in window coordinates the points are rasterized as wireframe.
     This is a very good exercise to learn how a vertex makes its way to the screen.<br><br>
     <a target="_blank" href="https://shadertoy.com/view/wtVSDh"> Link to the shader </a>
     
  - title: Blinn-Phong 3d3cWN
    shaderId: 3d3cWN
    description: |
     <br>A test of the Blinn-Phong model shading, that use  ambient + diffuse + specular. The specular component uses the Schlick's approximation to compute the
     Freshnel factor. Environment reflection are added from a cubemap. <br><br>
     <a target="_blank" href="https://shadertoy.com/view/3d3cWN"> Link to the shader </a>
    
#User specific content
#Links that will appear in the navbar
primarylinks:
# - title: Blog
#   url: https://automateddeveloper.blogspot.com/
# - title: GitHub
#   url: https://github.com/robhinds
# - title: StackOverflow
#   url: https://stackoverflow.com/users/258813/rhinds
# - title: DZone
#   url: https://dzone.com/users/899489/rhinds.html
# - title: LinkedIn
#   url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1

#Any buzzword skills you want to include
skills:
 - C++ 17
 - Direct3D 12
 - HLSL
 - PIX
 - Visual Studio
 - Math 
 - OpenGL
 - GLSL
 - Unreal Engine
 - Visual Studio Code
 - Java
 - Java Spring
 - Eclipse
 - MySQL / PostgreSQL / SQL
 - Javascript
 - HTML
 - CSS
 - Photoshop
 
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Back-end developer - Java
   start: 2016
   end: 2020
   employer: Synthesis3
   description: Synthesis3 is a company that develops software for the automotive field. Iveco or FPT Powertrain are among its clients. 
 - title: Full stack Mobile developer - Angular and PHP
   start: 2015
   end: 2016
   employer: JumpOn
   description: JumpOn was a start-up who provided mobility as a service. I worked as full stack developer on a mobile app for car sharing.
 - title: Front-end developer - Javascript, HTML 
   start: 2015
   end: 2016
   employer: I.See
   description: I.See is a company that develops Radioterapy Treatment Planning System software. As front end programmer I developed the user interface to visualize and interact with the 3D CT scans, defining the treatment plan.
 - title: Programmer and researcher - C++, Java and Python
   start: 2012
   end: 2015
   employer: University of Turin
   description: "As contract researcher I developed software, algorithms and protocols in collaboration with the research team. Some of the research fields were: social networks, recommending system and peer to peer protocols."
 - title: Full stack developer - Javascript, JQuery and PHP
   start: 2011
   end: 2012
   employer: Institut National de Recherche, France
   description: Development of mobile apps that implements services for citizens
 - title: Developer and researcher - C++ and OpenGL  
   start: 2005
   end: 2008
   employer: University of Catania
   description: As contract researcher I develop new protocols, algorithms and software releated to 3D medical imaging.
 - title: Developer - C++
   start: 2001
   end: 2002
   employer: Telecom Italia Lab
   description: Development of a Gsm/Gprs protocols simulation
 
#Education is required
education:
 - level: Ph.D 
   date: 2011
   subject: Computer Science
   school: University of Turin
 - level: Master Degree (110/110 cum laude)
   date: 2005
   subject: Computer Science
   school: University of Catania
 - level: University stage
   date: 2002
   subject: Development of a 3D laser scanner prototype
   school: University of Catania


#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  I am a computer scientist and a passionate software developer with 20 years of experience working in technology.
  During my career, I worked both on enterprise applications and in the applied research field.
  I have a strong algorithmic and mathematical background and I adapt very quickly to new languages and frameworks.
  During the past years, I collaborated on many projects, working with different teams and technologies.
  I have solid skills in 3D math and game-related algorithms. Always in love with video games.
  
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
#additionalinfo: | 
#   <strong>C++</strong>: Currently I am developing my personal projects using C++ 17 and HLSL. I I worked in the past on projects that used previous versions of the language, both at University and at Private companies <br/>
   
